apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bff-ingress
  namespace: food-rescue-live
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect-port: "8443"
    cert-manager.io/cluster-issuer: letsencrypt-http01
spec:
  ingressClassName: nginx
  rules:
    - host: asl.serveblog.net
      http:
        paths:
          - backend:
              service:
                name: bff-service # Routes to your BFF
                port:
                  number: 8090
            path: /api/ # This routes ALL API calls
            pathType: Prefix
  tls:
    - hosts:
        - asl.serveblog.net
      secretName: bff-service-tls # Re-use the same TLS secret