apiVersion: apps/v1
kind: Deployment
metadata:
  name: lots-service-deployment
  namespace: food-rescue-live # Using your confirmed namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lots-service
  template:
    metadata:
      labels:
        app: lots-service
    spec:
      containers:
        - name: lots-service
          # This image will be updated by our CI pipeline
          image: andresl123/lots-matching-service:latest
          ports:
            - containerPort: 8081 # Port from your properties file
      nodeSelector:
        kubernetes.io/arch: arm64