apiVersion: apps/v1
kind: Deployment
metadata:
  name: lots-service-deployment
  namespace: food-rescue-live # Using your confirmed namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lots-service
  template:
    metadata:
      labels:
        app: lots-service
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        runAsNonRoot: true
      containers:
        - name: lots-service
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          # This image will be updated by our CI pipeline
          image: andresl123/lots-matching-service:471b840
          ports:
            - containerPort: 8081 # Port from your properties file
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
      nodeSelector:
        kubernetes.io/arch: arm64
