apiVersion: apps/v1
kind: Deployment
metadata:
  name: evidence-service-deployment
  namespace: food-rescue-live
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evidence-service
  template:
    metadata:
      labels:
        app: evidence-service
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        runAsNonRoot: true
      containers:
        - name: evidence-service
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          image: andresl123/evidence-service:f3cb739
          ports:
            - containerPort: 8083

          # Activate the K8s profile
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"

      nodeSelector:
        kubernetes.io/arch: arm64
